amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    scan_topic: scan
    tf_broadcast: true
    transform_tolerance: 1.0
    save_pose_rate: 1.5

    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2

    laser_model_type: "likelihood_field"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    lambda_short: 0.1
    laser_likelihood_max_dist: 6.0
    laser_max_range: 12.0
    laser_min_range: 0.15
    max_beams: 60
    pf_err: 0.05
    pf_z: 0.99
    sigma_hit: 0.2
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

    resample_interval: 1
    max_particles: 2000
    min_particles: 500
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    update_min_a: 0.2
    update_min_d: 0.25